const listUser = [
  {
    name: 'Minh Toàn 0',
    coins: 2000,
    user: false,
    index: 0,
    status: true,
    nameWL: '',
    value: 0,
    statusMoney: '',
    checkMoney: true,
    images: [],
  },
  {
    name: 'Minh Toàn 1',
    coins: 2000,
    user: false,
    index: 1,
    status: true,
    nameWL: '',
    value: 0,
    statusMoney: '',
    checkMoney: false,
    images: [],
  },
  {
    name: 'Minh Toàn 2',
    coins: 2000,
    user: false,
    index: 2,
    status: true,
    nameWL: '',
    value: 0,
    statusMoney: '',
    checkMoney: true,
    images: [],
  },
  {
    name: 'Minh Toàn 3',
    coins: 2000,
    user: false,
    index: 3,
    status: true,
    nameWL: '',
    value: 0,
    statusMoney: '',
    checkMoney: true,
    images: [],
  },
]

export { listUser }
